spring.application.name=SpringBootMINIProj01-CRUDoperations

spring.mvc.view.prefix=/WEB-INF/pages/
spring.mvc.view.suffix=.jsp

server.port=4041

server.servlet.context-path=/Student-CRUDOperations

spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:ORCL
spring.datasource.username=leela
spring.datasource.password=prasad

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
